/*
CREATE THE DATABASE
*/
/*
CREATE USER 'minion'@'localhost' IDENTIFIED BY 'temp_pass';
CREATE DATABASE minion_training_facility;
GRANT SELECT,INSERT,DELETE,UPDATE ON minion_training_facility.* TO 'minion'@'localhost';
*/
USE minion_training_facility;

/*
CREATE THE TABLES
*/
DROP TABLE IF EXISTS players;
CREATE TABLE players (player_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64), password VARCHAR(64), secret VARCHAR(64), created TIMESTAMP DEFAULT '0000-00-00 00:00:00', last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE INDEX player ON players(username);

DROP TABLE IF EXISTS saves;
CREATE TABLE saves (save_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, player_id INT(32) UNSIGNED NOT NULL, save_number TINYINT(2) UNSIGNED DEFAULT 0, created TIMESTAMP DEFAULT '0000-00-00 00:00:00', last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE INDEX player_saves ON saves(player_id);

DROP TABLE IF EXISTS minions;
CREATE TABLE minions (minion_id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, save_id INT(32) UNSIGNED NOT NULL, minion_number TINYINT(2) UNSIGNED DEFAULT 0, name VARCHAR(64));
CREATE INDEX save_minions ON minions(save_id);
